name: Run API Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Run API Tests
        run: mvn test

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/
